#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && chezmoi edit "$HOME/.local/bin/$choice" && chezmoi apply -v "$HOME/.local/bin/$choice"
	;}
ce() {
	choice="$(find ~/.config -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.config/$choice" ] && chezmoi edit "$HOME/.config/$choice" && chezmoi apply -v "$HOME/.config/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i -o '%(title)s.%(ext)s' " \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	yt4="yt --format mp4 --embed-thumbnail" \
	ytp="yt4 --yes-playlist -o '%(playlist_index)s-%(title)s.%(ext)s'" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="lsd -h --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# Neo Commands
alias \
	sxiv="nsxiv" \
	vim="nvim"
# Todo commands
alias \
	ptodo="todo list personal --category personal" \
	shtodo="todo list personal --category shit" \
	mtodo="todo list personal --category money" \
	btodo="todo list personal --category backlog" \
	wtodo="todo list FLDPRFX_2F5BE02AFF824F0C85025B10B9D838E9" \
	jtodo="todo list personal --category jarbs" \
	stodo="todo list personal --category school" \
	htodo="echo \"ptodo, shtodo, mtodo, wtodo, jtodo, stodo\""
nstodo() {
	DUEDATE=$(date -d "+7 days" -u '+%d.%m.%Y')
	todo new --list personal --category school --due $DUEDATE $@
}

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	s="nsxiv" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	ll="ls -lah" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
