#!/bin/sh

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script

autostart="mpd dunst unclutter pipewire remapd"
picom --config /dev/null --vsync &

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
